### ISSUE TITLE
[Error] the production build is creating runtime errors

### ISSUE THREAD

**Issue by sp90** [gdi2290/ng4-universal-demo#6]
This is the error in the browser console, and thrown by express to the terminal aswell - for this to happen i ran these commands:

`npm run server` and `npm run build:prod`

And visit `localhost:8000`

```
GET: /: 7.428ms
Error: No NgModule metadata found for 'ServerAppModule'.
    at NgModuleResolver.resolve (/Users/simondragsbaek/Documents/dev/ng4-universal-demo/node_modules/@angular/compiler/bundles/compiler.umd.js:13889:23) [<root>]
    at CompileMetadataResolver.getNgModuleMetadata (/Users/simondragsbaek/Documents/dev/ng4-universal-demo/node_modules/@angular/compiler/bundles/compiler.umd.js:14473:60) [<root>]
    at JitCompiler._loadModules (/Users/simondragsbaek/Documents/dev/ng4-universal-demo/node_modules/@angular/compiler/bundles/compiler.umd.js:25640:66) [<root>]
    at JitCompiler._compileModuleAndComponents (/Users/simondragsbaek/Documents/dev/ng4-universal-demo/node_modules/@angular/compiler/bundles/compiler.umd.js:25599:52) [<root>]
    at JitCompiler.compileModuleAsync (/Users/simondragsbaek/Documents/dev/ng4-universal-demo/node_modules/@angular/compiler/bundles/compiler.umd.js:25561:23) [<root>]
    at PlatformRef_._bootstrapModuleWithZone (/Users/simondragsbaek/Documents/dev/ng4-universal-demo/node_modules/@angular/core/bundles/core.umd.js:4793:25) [<root>]
    at PlatformRef_.bootstrapModule (/Users/simondragsbaek/Documents/dev/ng4-universal-demo/node_modules/@angular/core/bundles/core.umd.js:4779:21) [<root>]
    at View.engine (/Users/simondragsbaek/Documents/dev/ng4-universal-demo/node_modules/@angularclass/universal-express/dist/index.js:35:73) [<root>]
    at View.render (/Users/simondragsbaek/Documents/dev/ng4-universal-demo/node_modules/express/lib/view.js:128:8) [<root>]
    at tryRender (/Users/simondragsbaek/Documents/dev/ng4-universal-demo/node_modules/express/lib/application.js:640:10) [<root>]
    at Function.render (/Users/simondragsbaek/Documents/dev/ng4-universal-demo/node_modules/express/lib/application.js:592:3) [<root>]
    at ServerResponse.render (/Users/simondragsbaek/Documents/dev/ng4-universal-demo/node_modules/express/lib/response.js:966:7) [<root>]
    at /Users/simondragsbaek/Documents/dev/ng4-universal-demo/dist/server.js:219:13 [<root>]
    at Layer.handle [as handle_request] (/Users/simondragsbaek/Documents/dev/ng4-universal-demo/node_modules/express/lib/router/layer.js:95:5) [<root>]
```

**Comment by sp90** [comment]
@gdi2290 Do you have any idear how to solve this, i've been at this for some time now and cant seem to solve it.

👍

**Comment by KissBalazs** [comment]
A workaround until the author answers: (from an old guilde a similar repository)

### Deploying to Linux
1. Install NodeJS if you haven't already.
2. Run the following command:
    ```sh
    npm install pm2 -g
    ```
3. Setup directory structure for production:
    ```sh
    mkdir %projectname%
    cd %projectname%
    mkdir prod
    ```
4. Remove source map files from files in ```dist``` directory.
5. Copy files inside ```dist``` directory to ```prod``` directory on your server.
6. ```cd``` to the root of your project directory on your server. You have to make sure that you are not inside the ```prod``` directory.
7. To start your app for production, run the following command:
    ```sh
    NODE_ENV=production pm2 start prod/server.js
    ```

This works for me at the moment.

**Comment by PatrickJS** [comment]
hey, yeah sorry I didn't think anyone would see this repo. I'll update the repo this week if not ping me again

**Comment by PatrickJS** [comment]
the repo is updated. please create another issue if you run into anything
